apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bpce-backend-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: REPO_URL
    targetRevision: main
    path: deploy/kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: bpce-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
