apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: bpce-kafka-pool
  namespace: bpce-platform
  labels:
    strimzi.io/cluster: bpce-kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
