apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: bpce-kafka
  namespace: bpce-platform
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: scram
        port: 9093
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
    config:
      default.replication.factor: 1
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
